name: Setup
description: Checks out the repository and installs tooling
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Cache dependencies
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      env:
        cache-name: bun-cache
      with:
        # Default as per docs 👇
        # https://bun.sh/docs/runtime/bunfig#install-cache
        path: ~/.bun/install/cache
        key: ${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
