#local_backend: true
backend:
  name: github
  repo: davidlj95/chrislb
  branch: main
  # 👇 To be in sync with Cloudflare Pages deploy previews
  preview_context: 'deploy/preview'
  cms_label_prefix: decap-cms/
  squash_merges: true
  commit_messages:
    create: 'feat(contents): create {{collection}} “{{slug}}”'
    update: 'feat(contents): update {{collection}} “{{slug}}”'
    delete: 'feat(contents): delete {{collection}} “{{slug}}”'
    uploadMedia: 'feat(media): upload “{{path}}”'
    deleteMedia: 'feat(media): delete “{{path}}”'
    openAuthoring: '{{message}}'
publish_mode: editorial_workflow
media_folder: 'public/cms/assets'
public_folder: '/cms/assets'
site_url: https://christianlazaro.es
display_url: https://github.com/davidlj95/chrislb
logo_url: https://christianlazaro.es/favicon.svg
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
editor:
  preview: false
field_definitions:
  - title: &title
      label: 'Title'
      name: 'title'
      widget: 'string'
  - slug: &slug
      label: 'Slug'
      name: 'slug'
      widget: 'string'
      pattern:
        [
          '^[a-z0-9-._]+$',
          'Must have at least 1 character. Must contain only lowercase alphabetic characters, numbers and hyphens (-)',
        ]
  - url: &url
      label: 'URL'
      name: 'url'
      widget: 'string'
      pattern: ['^https:\/\/.*', 'Must start with https://']
  - name: &name
      label: 'Name'
      name: 'name'
      widget: 'string'
  - username: &username
      label: 'Username'
      name: 'username'
      widget: 'string'
      pattern:
        [
          '^[^@].+$',
          'Must have at least 1 character. Must not start with @ (will be added automagically if needed 🪄)',
        ]
collections:
  - name: 'pages'
    label: 'Pages metadata'
    # 👇 Apparently only used in commit messages / PR titles
    # So lowercase is better for those contexts
    label_singular: 'page metadata'
    description: 'Metadata to use for each (static) page'
    folder: 'data/cms/pages'
    extension: 'json'
    create: false
    delete: false
    slug: '{{fields.slug}}'
    identifier_field: 'slug'
    preview_path: '{{slug}}'
    summary: '{{name}}'
    fields:
      - <<: *name
        hint: 'Identifies the page in the content manager. Also appears in navigation menu in case title is empty'
      - <<: *slug
        hint: '⚠️ Avoid updating without notifying developer :) Sets the page path in the URL. And the filename containing this configuration'
      - <<: *title
        hint: 'This will appear in page titles in browser tabs / windows. Including the site name. Something like: "<Page title> - <Site name>". For instance: "About | Christian Lazaro". Leave it empty to show site name only'
        required: false
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Keywords'
        name: 'keywords'
        widget: 'list'
        summary: '{{fields.keyword}}'
        required: false
        field:
          label: 'Keyword'
          name: 'keyword'
          widget: 'string'
      - label: 'Image'
        name: 'image'
        widget: 'object'
        required: false
        fields:
          - *url
          - label: 'Alternative text'
            name: 'alt'
            widget: 'string'
          - label: 'Width'
            name: 'width'
            widget: 'number'
            value_type: 'int'
            min: 256
          - label: 'Height'
            name: 'height'
            widget: 'number'
            value_type: 'int'
            min: 256
          - label: 'MIME Type'
            name: 'mimeType'
            widget: 'select'
            options:
              - label: 'PNG'
                value: 'image/png'
              - label: 'JPG / JPEG'
                value: 'image/jpeg'
              - label: 'SVG'
                value: 'image/svg+xml'
  - name: 'projects'
    label: 'Projects'
    label_singular: 'project'
    description: 'Projects to show in the projects page and their data'
    folder: 'data/cms/projects'
    extension: 'json'
    create: true
    slug: '{{fields.slug}}'
    identifier_field: 'slug'
    summary: '{{title}}'
    fields:
      - <<: *slug
        hint: '⚠️ Avoid updating "chiasma" one without notifying developer :) Sets the project path in the URL. Use it in the image CDN as directory name to include images for this project.'
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD'
        time_format: false
        format: 'YYYY-MM-DD'
        hint: 'Used to sort projects in list. Most recent first'
      - *title
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
      - label: 'Quote'
        name: 'quote'
        widget: 'string'
        required: false
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Credits'
        name: 'credits'
        widget: 'list'
        summary: '{{fields.role}}: {{fields.authorSlug}}'
        required: false
        fields:
          - label: 'Role'
            name: 'role'
            widget: 'string'
          - label: 'Author'
            name: 'authorSlug'
            widget: 'relation'
            collection: 'authors'
            search_fields: ['name']
            value_field: '{{slug}}'
            display_fields: ['{{name}}']
      - label: 'YouTube playlist ID'
        name: 'youtubePlaylistId'
        widget: 'string'
        required: false
        hint: 'In case you want to attach some videos, create a YouTube playlist with those videos. Then, click on share button in the playlist. Copy and paste the link, and extract whatever comes as list ID (after the "list" parameter). For instance, a sample link could be "https://youtube.com/playlist?list=PLbAKzQYf5_ME9HVqX2laYHNWCny96L5aI&si=zjfX69n2iqzZeVN4". In there, the playlist ID is "PLbAKzQYf5_ME9HVqX2laYHNWCny96L5aI"'
      - label: Albums
        name: albums
        widget: 'list'
        summary: '{{fields.presetSlug}}/{{fields.subdirectory}} {{fields.customTitle}}'
        required: false
        hint: 'An album is a set of images you want to display in the project details page. The album preset defines some configurations for it. Check album presets for more info. ‼️ Directory containing the album MUST exist, otherwise, site generation will fail. The directory containing the album images in the images CDN should be "projects/{projectSlug}/{albumPresetSlug}". Except if specifying a subdirectory (see more info there)'
        fields:
          - label: 'Album preset'
            name: 'presetSlug'
            widget: 'relation'
            collection: 'album-presets'
            search_fields: ['name']
            value_field: '{{slug}}'
            display_fields: ['{{name}}']
          - label: 'Subdirectory'
            name: 'subdirectory'
            required: false
            widget: 'string'
            hint: 'If you want more than one album of the same type, you can specify the subdirectory to look for images here. Then, the images for this album should be in `projects/{projectSlug}/{albumPresetSlug}/{subdirectory}` in the images CDN'
          - label: 'Custom title'
            name: 'customTitle'
            required: false
            widget: 'string'
            hint: 'In the case you want more than one album of the same type, maybe you want also a custom title apart from the album preset title. The final title for the album will then be: `{albumPresetTitle} {subAlbumIndex} "{customTitle}"`'
  - name: 'authors'
    label: 'Authors'
    label_singular: 'author'
    description: 'People that have participated in projects, for their appearance in credits. Also contains data to reflect author of the website'
    folder: 'data/cms/authors'
    extension: 'json'
    create: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{name}}'
    fields:
      - *name
      - label: 'Social'
        name: 'social'
        widget: 'object'
        fields:
          - label: 'Preferred social network'
            name: 'preferred'
            hint: 'Will be used in credits. If unset, defaults to default social network preference (see here: https://github.com/davidlj95/chrislb/blob/main/src/app/common/social/social.service.ts#L16-L18)'
            required: false
            widget: 'select'
            options:
              - label: 'Instagram'
                value: 'instagram'
              - label: 'LinkedIn'
                value: 'linkedin'
              - label: 'TikTok'
                value: 'tiktok'
          - <<: *username
            label: 'Instagram'
            name: 'instagram'
            hint: 'Used to link to Instagram profile (https://instagram.com/_u/<username>). To change yours: https://help.instagram.com/583107688369069'
            required: false
          - <<: *username
            label: 'LinkedIn'
            name: 'linkedin'
            required: false
            hint: 'Used to link to LinkedIn profile (https://linkedin.com/in/<username>). To create yours: https://www.linkedin.com/help/linkedin/answer/a542685'
          - <<: *username
            label: 'TikTok'
            name: 'tiktok'
            required: false
            hint: 'Used to link to TikTok profile (https://tiktok.com/@<username>). To change yours: https://support.tiktok.com/en/getting-started/setting-up-your-profile/changing-your-username'
  - name: 'album-presets'
    label: 'Album presets'
    label_singular: 'album preset'
    description: 'An album preset is a set of album predefined configurations. Which includes image directory in the CDN, its display name and its size in the page. To sort their appearance on screen, check the miscellaneous content collection'
    folder: 'data/cms/album-presets'
    extension: 'json'
    create: true
    slug: '{{fields.slug}}'
    identifier_field: '{{fields.slug}}'
    summary: '{{name}} ({{fields.slug}})'
    fields:
      - <<: *name
        hint: 'Name of the album in the project details page'
      - <<: *slug
        label: 'Slug (directory name in image CDN)'
        hint: '‼️ MUST match the name of the directory you will use for it inside each project in the image CDN. Otherwise, proper name will not be displayed'
      - label: 'Gallery size'
        name: 'size'
        hint: 'Specifies the size for the gallery when displaying the assets in the project detail page. Full size: will take as much space as possible. This means as much height as possible on big screens or full width on small screens. Half size: assets will take half of width in big screens. On small screens, will keep taking full width'
        widget: 'select'
        options:
          - label: 'Full'
            value: 'full'
          - label: 'Half'
            value: 'half'
  - name: 'misc'
    label: 'Miscellaneous'
    label_singular: 'miscellaneous'
    files:
      - label: 'Default metadata'
        name: 'metadata'
        file: 'data/cms/misc/metadata.json'
        fields:
          - label: 'Site name'
            name: 'siteName'
            widget: 'string'
            hint: 'This will appear in page titles in browser tabs / windows. Including the page title. Something like: "<Page title> - <Site name>". For instance: "About | Christian Lazaro"'
          - label: 'Author'
            name: 'author'
            widget: 'string'
          - <<: *url
            label: 'Canonical URL'
            name: 'canonicalUrl'
      - label: 'About page'
        name: 'about'
        file: 'data/cms/misc/about.json'
        preview_path: 'about'
        fields:
          - *title
          - label: 'Text'
            name: 'text'
            widget: 'text'
          - label: 'Open Graph profile'
            name: 'openGraphProfile'
            widget: 'object'
            hint: 'Will be used as metadata to describe this page represents this person on the Internet. More info: https://ogp.me/#type_profile'
            fields:
              - label: 'First name'
                name: 'firstName'
                widget: 'string'
              - label: 'Last name'
                name: 'lastName'
                widget: 'string'
              - label: 'Gender'
                widget: 'select'
                name: 'gender'
                required: false
                hint: 'Will only be used for main website author metadata. Unfortunately specification only accepts male or female 😬'
                options:
                  - label: 'Male'
                    value: 'male'
                  - label: 'Female'
                    value: 'female'
              - <<: *username
                label: 'Main username'
                name: 'username'
                required: false
          - label: 'Resume'
            name: 'resume'
            widget: 'list'
            summary: '{{fields.displayName}}: {{fields.href}}'
            fields:
              - label: 'Display name'
                name: 'displayName'
                widget: 'string'
                hint: 'Name to display with link to this CV file'
              - label: 'File'
                name: 'href'
                widget: 'file'
                media_library:
                  allow_multiple: false
                  config:
                    multiple: false
