#local_backend: true
backend:
  name: github
  repo: davidlj95/chrislb
  branch: main
  # 👇 To be in sync with Cloudflare Pages deploy previews
  preview_context: 'deploy/preview'
  cms_label_prefix: decap-cms/
  squash_merges: true
  commit_messages:
    create: 'feat(contents): create {{collection}} “{{slug}}”'
    update: 'feat(contents): update {{collection}} “{{slug}}”'
    delete: 'feat(contents): delete {{collection}} “{{slug}}”'
    uploadMedia: 'feat(media): upload “{{path}}”'
    deleteMedia: 'feat(media): delete “{{path}}”'
    openAuthoring: '{{message}}'
publish_mode: editorial_workflow
media_folder: 'src/assets/cms'
public_folder: '/assets/cms'
site_url: https://christianlazaro.es
display_url: https://github.com/davidlj95/chrislb
logo_url: https://christianlazaro.es/favicon.svg
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
editor:
  preview: false
field_definitions:
  - title: &title
      label: 'Title'
      name: 'title'
      widget: 'string'
  - slug: &slug
      label: 'Slug'
      name: 'slug'
      widget: 'string'
      pattern:
        [
          '^[a-z0-9-._]+$',
          'Must have at least 1 character. Must contain only lowercase alphabetic characters, numbers and hyphens (-)',
        ]
  - url: &url
      label: 'URL'
      name: 'url'
      widget: 'string'
      pattern: ['^https:\/\/.*', 'Must start with https://']
  - name: &name
      label: 'Name'
      name: 'name'
      widget: 'string'
  - username: &username
      label: 'Username'
      name: 'username'
      widget: 'string'
      pattern:
        [
          '^[^@]*+',
          'Must have at least 1 character. Must not start with @ (will be added automagically if needed 🪄)',
        ]
collections:
  - name: 'pages'
    label: 'Pages'
    # 👇 Apparently only used in commit messages / PR titles
    # So lowercase is better for those contexts
    label_singular: 'page'
    folder: 'src/data/pages'
    extension: 'json'
    create: false
    delete: false
    slug: '{{fields.slug}}'
    identifier_field: 'slug'
    preview_path: '{{slug}}'
    summary: '{{name}}'
    fields:
      - <<: *name
        hint: 'Identifies the page in the content manager. But nothing a visitor would see'
      - <<: *slug
        hint: '⚠️ Avoid updating without notifying developer :) Sets the page path in the URL. And the filename containing this configuration'
      - <<: *title
        hint: 'This will appear in page titles in browser tabs / windows. Including the site name. Something like: "<Page title> - <Site name>". For instance: "About | Christian Lazaro". Leave it empty to show site name only'
        required: false
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Keywords'
        name: 'keywords'
        widget: 'list'
        summary: '{{fields.keyword}}'
        required: false
        field:
          label: 'Keyword'
          name: 'keyword'
          widget: 'string'
      - label: 'Image'
        name: 'image'
        widget: 'object'
        required: false
        fields:
          - *url
          - label: 'Alternative text'
            name: 'alt'
            widget: 'string'
          - label: 'Width'
            name: 'width'
            widget: 'number'
            value_type: 'int'
            min: 256
          - label: 'Height'
            name: 'height'
            widget: 'number'
            value_type: 'int'
            min: 256
          - label: 'MIME Type'
            name: 'mimeType'
            widget: 'select'
            options:
              - label: 'PNG'
                value: 'image/png'
              - label: 'JPG / JPEG'
                value: 'image/jpeg'
              - label: 'SVG'
                value: 'image/svg+xml'
  - name: 'projects'
    label: 'Projects'
    label_singular: 'project'
    folder: 'src/content/projects'
    extension: 'json'
    create: true
    slug: '{{fields.slug}}'
    identifier_field: 'slug'
    summary: '{{title}}'
    fields:
      - <<: *slug
        hint: '⚠️ Avoid updating "chiasma" one without notifying developer :) Sets the project path in the URL. Use it in the image CDN as directory name to include images for this project.'
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD'
        time_format: false
        format: 'YYYY-MM-DD'
      - *title
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
      - label: 'Quote'
        name: 'quote'
        widget: 'string'
        required: false
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Credits'
        name: 'credits'
        widget: 'list'
        summary: '{{fields.role}}: {{fields.authorSlug}}'
        required: false
        fields:
          - label: 'Role'
            name: 'role'
            widget: 'string'
          - label: 'Author'
            name: 'authorSlug'
            widget: 'relation'
            collection: 'authors'
            search_fields: ['name', 'social.instagram']
            value_field: '{{slug}}'
            display_fields: ['{{name}} ({{social.instagram}})']
  - name: 'authors'
    label: 'Authors'
    label_singular: 'author'
    folder: 'src/data/authors'
    extension: 'json'
    create: true
    slug: '{{slug}}'
    identifier_field: 'name'
    summary: '{{firstName}} {{lastName}}'
    fields:
      - label: 'First name'
        name: 'firstName'
        widget: 'string'
      - label: 'Last name'
        name: 'lastName'
        widget: 'string'
      - label: 'Gender'
        widget: 'select'
        name: 'gender'
        required: false
        hint: 'Will only be used for main website author metadata. Unfortunately specification only accepts male or female 😬 . More info: https://ogp.me/#type_profile'
        options:
          - label: 'Male'
            value: 'male'
          - label: 'Female'
            value: 'female'
      - <<: *username
        required: false
        hint: 'Will only be used for main website author metadata. More info: https://ogp.me/#type_profile'
      - label: 'Social'
        name: 'social'
        widget: 'object'
        fields:
          - <<: *username
            label: 'Instagram'
            name: 'instagram'
            hint: 'Used to link to Instagram profile (https://instagram.com/_u/<username>). To change yours: https://help.instagram.com/583107688369069'
            required: false
          - <<: *username
            label: 'LinkedIn'
            name: 'linkedin'
            required: false
            hint: 'Used to link to LinkedIn profile (https://linkedin.com/in/<username>). To create yours: https://www.linkedin.com/help/linkedin/answer/a542685'
          - <<: *username
            label: 'TikTok'
            name: 'tiktok'
            required: false
            hint: 'Used to link to TikTok profile (https://tiktok.com/@<username>). To change yours: https://support.tiktok.com/en/getting-started/setting-up-your-profile/changing-your-username'
  - name: 'misc'
    label: 'Miscellaneous'
    files:
      - label: 'Default metadata'
        name: 'metadata'
        file: 'src/data/misc/metadata.json'
        fields:
          - label: 'Site name'
            name: 'siteName'
            widget: 'string'
            hint: 'This will appear in page titles in browser tabs / windows. Including the page title. Something like: "<Page title> - <Site name>". For instance: "About | Christian Lazaro"'
          - label: 'Author'
            name: 'author'
            widget: 'string'
          - <<: *url
            label: 'Canonical URL'
            name: 'canonicalUrl'
      - label: 'Lookbook names by slug'
        name: 'names-by-slug'
        file: 'src/data/misc/lookbook-names-by-slug.json'
        fields:
          - label: 'Names by slug'
            name: 'namesBySlug'
            widget: 'list'
            hint: 'Maps the slugs (directory names in the image CDN) to names to display in the website'
            summary: '{{fields.slug}}: {{fields.name}}'
            fields:
              - *slug
              - *name
      - label: 'About page'
        name: 'about'
        file: 'src/data/misc/about.json'
        preview_path: 'about'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Text'
            name: 'text'
            widget: 'text'
          - label: 'Resume'
            name: 'resume'
            widget: 'list'
            summary: '{{fields.displayName}}: {{fields.href}}'
            fields:
              - label: 'Display name'
                name: 'displayName'
                widget: 'string'
                hint: 'Name to display with link to this CV file'
              - label: 'File'
                name: 'href'
                widget: 'file'
                media_library:
                  allow_multiple: false
                  config:
                    multiple: false
