name: Performance
on:
  workflow_call:
    secrets:
      LHCI_GITHUB_APP_TOKEN:
        required: true

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download built app
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: build
      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          # Needed for status checks to appear on PR
          # https://github.com/GoogleChrome/lighthouse-ci/issues/859#issuecomment-1574205125
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        run: pnpm run test:app:lighthouse
